name: Hello World Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: run my action
        uses: garygrossgarten/billy-github-action@release
        with:
          name: Gary

        env:
          CI: true
