name: Hello World Example

on:
  push:
    branches: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run my action
        uses: garygrossgarten/billy-github-action@release
        with:
          name: Gary

        env:
          CI: true
